# Generated by Django 4.0.5 on 2022-07-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id_message', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('message_text', models.CharField(max_length=200)),
            ],
        ),
    ]
